name: Generate CV
on:
  push:
    branches:
      - main
    paths:
      - '*.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV-Jan_van_den_Berg.tex

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            CV-Jan_van_den_Berg.pdf
